version: '3.5'

services:

  nginx:
    image: nginx:stable
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - php
    container_name: cont_nginx

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    environment:
        - PHP_IDE_CONFIG=serverName=laravelshopserver
    depends_on:
      - db
    container_name: cont_php

  db:
    image: mysql:8.0
    #command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
        - "8101:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: cont_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - "8181:80"
    environment:
        - PMA_ARBITRARY=1
    depends_on:
        - db

  node:
    container_name: cont_node
    build:
        dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
        - ./:/app
#    ports:
#        - "5173:5173"
